export const PERMISSIONS = {
  MANAGE_USERS: 'MANAGE_USERS',
  APPROVE_MEMBERS: 'APPROVE_MEMBERS',
  VIEW_USERS: 'VIEW_USERS',
  CREATE_POSTS: 'CREATE_POSTS',
  MANAGE_POSTS: 'MANAGE_POSTS',
  CREATE_POLLS: 'CREATE_POLLS',
  MANAGE_POLLS: 'MANAGE_POLLS',
  VIEW_PAYMENTS: 'VIEW_PAYMENTS',
  MANAGE_PAYMENTS: 'MANAGE_PAYMENTS',
  SEND_NOTIFICATIONS: 'SEND_NOTIFICATIONS',
  MANAGE_ROLES: 'MANAGE_ROLES',
  ASSIGN_ROLES: 'ASSIGN_ROLES',
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
};

export const RELATION_LABELS = {
  FATHER: 'Father',
  MOTHER: 'Mother',
  WIFE: 'Wife',
  HUSBAND: 'Husband',
  SON: 'Son',
  DAUGHTER: 'Daughter',
  BROTHER: 'Brother',
  SISTER: 'Sister',
  OTHER: 'Other',
};

export const PAYMENT_STATUS_COLORS = {
  PAID: '#22c55e',
  PENDING: '#f59e0b',
  FAILED: '#ef4444',
  REFUNDED: '#6366f1',
};
